### ISSUE TITLE
Add a link to your public-facing instance of this project to the README, if you have one

### ISSUE THREAD

**Issue by DeflateAwning** [disk91/helium-chirpstack-community#91]
I'd love to give this project a try on the instance you're hosting, if you have one! 

If the only one you're hosting is https://dev.helium-iot.eu/ (which seems to me like it's a dev/staging site), just note that it appears to be down.

**Comment by disk91** [comment]
sure ! the console is accessible on https://console.helium-iot.xyz

**Comment by DeflateAwning** [comment]
Awesome, thanks! Fixed in https://github.com/disk91/helium-chirpstack-community/commit/c0cc68b1299a60468c5b0597369a7a88468c723d
