### ISSUE TITLE
encrypted mqtt

### ISSUE THREAD

**Issue by dirkbeer** [disk91/helium-chirpstack-community#97]
I'm having trouble connecting to encrypted mqtt brokers. Here is my configuration:

![image](https://github.com/disk91/helium-chirpstack-community/assets/6425332/ffc37de1-915c-421c-ac6d-95b8626e7959)

Unencrypted works fine like this:

![image](https://github.com/disk91/helium-chirpstack-community/assets/6425332/ebb3a6b0-64fc-4107-9756-4605213f5888)

Am I doing something wrong, or is this a limitation of Chirpstack or of the forwarder?

**Comment by nikito7** [comment]
It works.

```
mqtts://user:password@mqtt.server:8883
```

![20240823_171831](https://github.com/user-attachments/assets/43eb7a7a-6b87-4d38-ac93-705928298089)
