### ISSUE TITLE
Frame Analysis request

### ISSUE THREAD

**Issue by chelliwell** [disk91/helium-chirpstack-community#98]
The Frame Analysis page is very useful, but it'd be even better if it were possible to filter on a date range.

**Comment by disk91** [comment]
Donyou mean you see too many frames at a time ? What would you want to filter with this feature ? (Try to understand the probelm to face)

**Comment by chelliwell** [comment]
As I understand it, it's showing me the hotspots that the selected device has reached. 
The Last Messages list seems to show the full history of about 2 days, so I presume these are the frames shown on the map too? 
What I was looking for was to be able to choose the date/time range which is displayed.

**Comment by disk91** [comment]
Sorry, I miss your response: if you click on a frame in the list, it will update the map with the hotspot having received this frame.
